<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0;net48</TargetFrameworks>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NETSDK1138</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ReorderableConcurrentQueue\ReorderableConcurrentQueue.csproj" />
  </ItemGroup>

</Project>
